tap homebrew/core

brew asdf
brew clang-format
brew direnv
brew gh
brew ghq
brew git
brew hugo
brew jq
brew mas
brew mercurial
brew neovim
brew nghttp2
brew openssl
brew packer
brew peco
brew telnet
brew tig

brew genkiroid/homebrew-cert/cert
brew rcmdnk/file/brew-file

cask alfred
cask appcleaner
cask docker
cask franz
cask google-chrome
cask google-cloud-sdk
cask google-drive
cask iterm2
cask notable
cask sequel-pro
cask spectacle
cask tunnelblick
cask visual-studio-code
cask vivaldi
cask wireshark

appstore 409183694 Keynote
appstore 409201541 Pages
appstore 409203825 Numbers
appstore 414298354 ToyViewer
appstore 441258766 Magnet
appstore 445189367 PopClip
appstore 1233965871 ScreenBrush
appstore 1429033973 RunCat
