tap homebrew/core

brew ansible
brew clang-format
brew direnv
brew ghq
brew git
brew jq
brew mas
brew mercurial
brew neovim
brew nghttp2
brew openssl
brew packer
brew peco
brew tig

brew genkiroid/homebrew-cert/cert
brew rcmdnk/file/brew-file

tap sanemat/font
brew ricty --with-powerline

cask 1password
cask alfred
cask appcleaner
cask boostnote
cask docker
cask dropbox
cask firefox
cask google-chrome
cask hosts
cask iterm2
cask scroll-reverser
cask sequel-pro
cask spectacle
cask tunnelblick
cask typora
cask vagrant
cask virtualbox
cask visual-studio-code
cask vivaldi
cask wireshark

appstore 409183694 Keynote
appstore 409201541 Pages
appstore 409203825 Numbers
appstore 412448059 ForkLift
appstore 414298354 ToyViewer
appstore 445189367 PopClip
appstore 880001334 Reeder
appstore 957734279 TogglDesktop
