tap homebrew/core
brew ansible
brew clang-format
brew ghq
brew git
brew go
brew jq
brew mas
brew mercurial
brew neovim
brew nghttp2
brew openssl
brew packer
brew peco
brew tig

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty --powerline --vim-powerline

cask alfred
cask appcleaner
cask boostnote
cask chicken
cask cyberduck
cask docker
cask dropbox
cask firefox
cask franz
cask google-chrome
cask hosts
cask iterm2
cask scroll-reverser
cask slack
cask spectacle
cask tunnelblick
cask typora
cask vagrant
cask virtualbox
cask vivaldi
cask wireshark

appstore 412448059 ForkLift
appstore 409183694 Keynote
appstore 409203825 Numbers
appstore 928941247 OTP Manager
appstore 409201541 Pages
appstore 445189367 PopClip
appstore 880001334 Reeder
appstore 957734279 TogglDesktop
appstore 414298354 ToyViewer
