[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
nnoremap  [denite]  <Nop>
nmap      ;        [denite]
nnoremap  <silent> [denite]b    :<C-u>Denite -auto-preview -mode=normal buffer<CR>
nnoremap  <silent> [denite]f    :<C-u>DeniteProjectDir file_rec<CR>
nnoremap  <silent> [denite]g    :<C-u>Denite grep -mode=normal<CR>
nnoremap  <silent> [denite]l    :<C-u>Denite line<CR>
nnoremap  <silent> [denite]d    :<C-u>Denite <Space>
'''

[[plugins]]
repo = 'harasou/quickmemo.vim'
hook_add = '''
let quickmemo_save_path = "~/.notable/%Y/%m"
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'fugitive', 'filename' ] ]
      \ },
      \ 'component_function': {
      \   'fugitive': 'LightLineFugitive',
      \   'readonly': 'LightLineReadonly',
      \   'modified': 'LightLineModified',
      \   'filename': 'LightLineFilename'
      \ },
	  \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
	  \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" }
      \ }

function! LightLineModified()
  if &filetype == "help"
    return ""
  elseif &modified
    return "+"
  elseif &modifiable
    return ""
  else
    return ""
  endif
endfunction

function! LightLineReadonly()
  if &filetype == "help"
    return ""
  elseif &readonly
    return "\ue0a2"
  else
    return ""
  endif
endfunction

function! LightLineFugitive()
  if exists("*fugitive#head")
    let branch = fugitive#head()
    return branch !=# '' ? "\ue0a0 ".branch : ''
  endif
  return ''
endfunction

function! LightLineFilename()
  return ('' != LightLineReadonly() ? LightLineReadonly() . ' ' : '') .
       \ ('' != expand('%:t') ? expand('%:t') : '[No Name]') .
       \ ('' != LightLineModified() ? ' ' . LightLineModified() : '')
endfunction
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
add_hook = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'zchee/deoplete-go'

[[plugins]]
repo = 'benekastah/neomake'

[[plugins]]
repo = 'fatih/vim-go'
add_hook = '''
let g:go_fmt_command = "goimports"
'''

[[plugins]]
repo = 'jakwings/vim-colors'
